define(["jquery", "snapsvg"], function( $, Snap ) {

	'use strict';

	var module = {},
	    stage = null,
		viewport = null;

	module.getStage = function(stage_id) {

		if (stage) return stage;

		stage = new Snap()
			.attr({
				"id": stage_id,
				"class": "pannable"
			});

		stage = stage.node;

		// clean up unwanted desc element generated by SnapSVG
		$(stage).children("desc:first").remove();
		return stage;
	};

	module.getViewport = function(viewport_id){
		if (viewport) return viewport;

		viewport = Snap(stage).g().attr({
			"id": viewport_id
		});

		// create dummy scene for SVGPanZoom
		var placeholder = viewport.rect(0,0,1026,546).attr({
			"opacity": "0",
			"class": "no-pointer-events"
		});

		// Method to remove the dummy object after first render
		module.removePlaceholder = function(){
			placeholder.remove();
			placeholder = null;
			delete module.removePlaceholder;
		};

		viewport = viewport.node;
		return viewport;
	};

	return module;
});