// Map lot id to redux tile

export default {
	// Corners
	"CORNER-BOTTOM": "TILE-CORNER-BOTTOM",
	"CORNER-LEFT": "TILE-CORNER-LEFT",
	"CORNER-TOP": "TILE-CORNER-TOP",
	"CORNER-RIGHT": "TILE-CORNER-RIGHT",

	// South
	"LOT-S08": "TILE-SOUTH-4",
	"LOT-S07": "TILE-SOUTH-5",
	"LOT-S06": "TILE-SOUTH-6",
	"LOT-S05": "TILE-SOUTH-7",
	"LOT-S04": "TILE-SOUTH-8",
	"LOT-S03": "TILE-SOUTH-9",
	"LOT-S02": "TILE-SOUTH-10",
	"LOT-S01": "TILE-SOUTH-11",
	"LOT-S00": "TILE-SOUTH-12",

	// West
	"LOT-W08": "TILE-WEST-4",
	"LOT-W07": "TILE-WEST-5",
	"LOT-W06": "TILE-WEST-6",
	"LOT-W05": "TILE-WEST-7",
	"LOT-W04": "TILE-WEST-8",
	"LOT-W03": "TILE-WEST-9",
	"LOT-W02": "TILE-WEST-10",
	"LOT-W01": "TILE-WEST-11",
	"LOT-W00": "TILE-WEST-12",

	// North
	"LOT-N00": "TILE-NORTH-4",
	"LOT-N01": "TILE-NORTH-5",
	"LOT-N02": "TILE-NORTH-6",
	"LOT-N03": "TILE-NORTH-7",
	"LOT-N04": "TILE-NORTH-8",
	"LOT-N05": "TILE-NORTH-9",
	"LOT-N06": "TILE-NORTH-10",
	"LOT-N07": "TILE-NORTH-11",
	"LOT-N08": "TILE-NORTH-12",

	// East
	"LOT-E00": "TILE-EAST-4",
	"LOT-E01": "TILE-EAST-5",
	"LOT-E02": "TILE-EAST-6",
	"LOT-E03": "TILE-EAST-7",
	"LOT-E04": "TILE-EAST-8",
	"LOT-E05": "TILE-EAST-9",
	"LOT-E06": "TILE-EAST-10",
	"LOT-E07": "TILE-EAST-11",
	"LOT-E08": "TILE-EAST-12",
};