import gRandom from "./utils/gaussianRandom";
import round100 from "./utils/round100";
import summation from "./utils/summation";

// Upgrade to tier 1
const TIER_1 = {
	min: 500,
	avg: 1250,
	max: 2000,
};
// Upgrade to tier 2
const TIER_2 = {
	min: 700,
	avg: 2000,
	max: 3500,
};
// Upgrade to tier 3
const TIER_3 = {
	min: 1500,
	avg: 2250,
	max: 4500,
};
// Upgrade to tier 4
const TIER_4 = {
	min: 2000,
	avg: 3500,
	max: 6000,
};

/**
 * A number representing a tier of a property.
 * Should be a integer in string format.
 * @typedef {string} Tier
 */

/**
 * Generate upgrade cost
 * @type {Object.<Tier, number>} Upgrade cost
 */
export default function () {
	// Upgrade cost were generated by taking sample from a normal distribution
	const base_cost = [
		gRandom(TIER_1.min, TIER_1.avg, TIER_1.max),
		gRandom(TIER_2.min, TIER_2.avg, TIER_2.max),
		gRandom(TIER_3.min, TIER_3.avg, TIER_3.max),
		gRandom(TIER_4.min, TIER_4.avg, TIER_4.max),
	];

	// Value of each tiers were stacked (increasing) from previous tier
	const stacked_cost = base_cost.map(function (v, idx, arr) {
		// An array of every value from index 0 to idx
		const prevValues = arr.slice(0, idx + 1);

		// Rent of each tier were added with previous tier
		const sum = prevValues.reduce(summation);

		// Round result to increments of 100
		return round100(sum);
	});

	//
	// Convert into object and make key starts with one:
	//

	// Fill tier zero with a placeholder (null)
	// Convert into key/value object and remove the placeholder
	stacked_cost.unshift(null);
	let converted = Object.assign({}, stacked_cost);
	delete converted["0"];

	return converted;
}